#!/usr/bin/env node
// Regenerate assets/icon.ico and assets/icon.png from the shared
// buildRawIcon() defined in ../icon-gen.js. Wired as the "prebuild"
// npm hook so every electron-builder invocation starts from a
// freshly-rendered icon that matches the runtime tray / window icon
// exactly. Before 1.4.6 the .ico was a stale binary that had to be
// regenerated by hand — which no one did, so tray / taskbar / shortcut
// icons silently drifted apart whenever the drawing code changed.

'use strict';

const fs = require('fs');
const path = require('path');
const { buildRawIcon, encodePNG, buildIco } = require('../icon-gen');

const ROOT = path.resolve(__dirname, '..');
const ASSETS = path.join(ROOT, 'assets');

if (!fs.existsSync(ASSETS)) fs.mkdirSync(ASSETS, { recursive: true });

// assets/icon.png is used for macOS builds + BrowserWindow.icon fallback.
// Render at 512x512 for a crisp macOS Retina Dock icon.
const bigRaw = buildRawIcon(512);
const bigPng = encodePNG(bigRaw.W, bigRaw.H, bigRaw.px);
fs.writeFileSync(path.join(ASSETS, 'icon.png'), bigPng);
console.log('[gen-icon] wrote assets/icon.png (' + bigPng.length + ' bytes, 512x512)');

// assets/icon.ico is the source Windows uses for the .exe's embedded
// icon — which is what Windows renders on the taskbar + desktop and
// Start Menu shortcuts. Embedding multiple sizes gives Explorer a
// clean render at every zoom level from 16px taskbar ticks up to
// 256px large-icon folder views.
const ico = buildIco([16, 24, 32, 48, 64, 128, 256]);
fs.writeFileSync(path.join(ASSETS, 'icon.ico'), ico);
console.log('[gen-icon] wrote assets/icon.ico (' + ico.length + ' bytes, 7 sizes embedded)');
